### ISSUE TITLE
error - aborted - on emacs 24.3.1 windows

### ISSUE THREAD

**Issue by ipstone** [jschaf/esup#8]
Starting esup...
(New file)
error in process sentinel: esup-read-results: End of file during parsing
error in process sentinel: End of file during parsing

**Comment by larstvei** [comment]
Hi!

I have a similar problem that I think occurs when loading idle-require.
```
esup: loading /Users/larstvei/.emacs.d/elpa/idle-require-20090715.1503/idle-require.elc
esup-child-profile-sexp: End of file during parsing
```

I've had similar issues with this package before. Perhaps one could make it default to loading `.el` files instead of `.elc` files?

I am running Emacs 24.4.1 on OS X.

I really like the package! I tried fixing this myself, but haven't found a fix so far. If you don't have time to fix this, perhaps you could point me in the right direction?
